spring:
  datasource:
    # url: jdbc:mysql://localhost:13306/zhyw_by?useUnicode=true&characterEncoding=UTF8&useSSL=false
    url: jdbc:mysql://117.78.36.177:3306/new_lumlord_2?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: lumlord
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl